// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqtudT9oYgDNQ1Cy8K9yDrPr52iYgmVy8',
    appId: '1:990593233395:android:77c0cf84e78f8926e92286',
    messagingSenderId: '990593233395',
    projectId: 'pickme-f0d3a',
    databaseURL: 'https://pickme-f0d3a-default-rtdb.firebaseio.com',
    storageBucket: 'pickme-f0d3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH0DPz1Pk-uoHsviCr3szCs6JAgljv4SM',
    appId: '1:990593233395:ios:e98875785b2dd429e92286',
    messagingSenderId: '990593233395',
    projectId: 'pickme-f0d3a',
    databaseURL: 'https://pickme-f0d3a-default-rtdb.firebaseio.com',
    storageBucket: 'pickme-f0d3a.appspot.com',
    iosClientId: '990593233395-qgcrkt56l256tmu8ijhfijptl6a1r1oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickmeMobile',
  );

}